import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
const { chromium }=await import(process.env.F003_PLAYWRIGHT_MODULE || '/Volumes/WorkSSD/clowder-ai/node_modules/playwright/index.mjs');
const browser=await chromium.launch({headless:true,executablePath:process.env.F003_CHROMIUM || '/Users/skybowen/Library/Caches/ms-playwright/chromium_headless_shell-1243/chrome-headless-shell-mac-arm64/chrome-headless-shell'});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:2});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const checks=[];const passed=label=>{checks.push(label);process.stdout.write(`PASS ${label}\n`);};
const dir=fileURLToPath(new URL('./evidence/',import.meta.url));
await mkdir(dir,{recursive:true});
try {
  const response=await page.goto('http://127.0.0.1:4317');assert.equal(response.status(),200);
  await page.locator('.graph-layout').waitFor();
  assert.equal((await page.request.get('http://127.0.0.1:4317/demo-contract.md')).status(),404);
  assert.equal((await page.request.post('http://127.0.0.1:4317/')).status(),405);
  await page.screenshot({path:dir+'01-graph-desktop.png',fullPage:true});
  assert.match(await page.locator('.truth').innerText(),/演示数据.*未连接后端/);passed('explicit prototype truth label');
  await page.locator('[data-action="view"][data-view="implementation"]').click();
  assert.equal(await page.locator('.node.shared').count(),1);
  await page.screenshot({path:dir+'09-implementation-neighbor.png',fullPage:true});
  await page.locator('[data-action="view"][data-view="coverage"]').click();
  assert.equal(await page.locator('.coverage-cell').count(),4);
  await page.locator('[data-action="view"][data-view="business"]').click();passed('same-graph view switching + shared-material neighbor');
  await page.locator('.node[data-id="test"]').click();
  assert.match(await page.locator('.inspector').innerText(),/没有关联执行记录.*不能推断测试通过/s);
  await page.locator('.inspector [data-action="source"]').click();
  assert.match(await page.locator('.modal').innerText(),/expect\(order.status\)/);
  await page.screenshot({path:dir+'02-source-evidence.png',fullPage:true});
  await page.locator('.modal [data-action="source-to-function"][data-id="stock"]').click();
  assert.match(await page.locator('.node.root').innerText(),/库存预占/);passed('source evidence + reverse-query navigation');
  await page.locator('#human-filter').check();
  assert.equal(await page.locator('.function-button').count(),2);
  assert.match(await page.locator('.node.root').innerText(),/支付与回调/);passed('human-only filtering does not promote Agent functions');
  await page.locator('#human-filter').uncheck();
  await page.locator('.tab[data-page="review"]').click();
  await page.screenshot({path:dir+'03-review-workspace.png',fullPage:true});
  await page.locator('[data-action="confirm-decision"]').click();
  assert.match(await page.locator('#review-error').innerText(),/依据/);
  const sentinel='QA-sentinel-范围83：采用默认实现，生产覆盖值仍待证。';
  await page.locator('input[name="choice"][value="code"]').check();
  await page.locator('#decision-reason').fill(sentinel);
  await page.locator('[data-action="confirm-decision"]').click();
  assert.match(await page.locator('[data-testid="decision-record"]').innerText(),/QA-sentinel-范围83/);
  await page.reload();await page.locator('.tab[data-page="review"]').click();
  assert.ok((await page.locator('[data-testid="decision-record"]').innerText()).includes(sentinel));
  await page.locator('[data-action="view-decision-graph"]').click();
  assert.match(await page.locator('.node.rule').innerText(),/人工确认/);
  assert.match(await page.locator('.node.root').innerText(),/Agent 分析/);passed('sentinel decision persists across refresh; only proposition confirmed');
  await page.locator('.tab[data-page="review"]').click();
  await page.locator('[data-action="question"][data-id="coupon"]').click();
  await page.locator('#decision-reason').fill('QA-defer-94：需要业务范围补充。');
  await page.locator('[data-action="defer"]').click();
  assert.match(await page.locator('[data-testid="decision-record"]').innerText(),/未升级为人工确认/);passed('deferral remains unresolved');
  await page.locator('.tab[data-page="materials"]').click();
  await page.screenshot({path:dir+'04-material-coverage.png',fullPage:true});
  await page.locator('[data-action="source"][data-id="restricted"]').click();
  assert.match(await page.locator('.modal').innerText(),/权限不足，不能显示内容/);
  assert.equal(await page.locator('.modal .code').count(),0);
  await page.keyboard.press('Escape');passed('restricted material retained without fabricated content');
  await page.locator('[data-action="new-run"]').first().click();
  await page.locator('#run-name').fill('QA-sentinel-run-27');
  await page.locator('#reference-version').selectOption('V11');
  assert.equal(await page.locator('#start-run').isDisabled(),true);
  await page.screenshot({path:dir+'05-blocked-preflight.png',fullPage:true});
  await page.locator('#reference-version').selectOption('V12');
  await page.locator('#start-run').click();
  assert.match(await page.locator('.runitem').innerText(),/QA-sentinel-run-27/);
  await page.locator('[data-step="pause"]').click();
  assert.equal(await page.locator('[data-step="advance"]').count(),0);
  await page.locator('[data-step="resume"]').click();
  await page.locator('[data-step="advance"]').click();
  assert.match(await page.locator('.runitem').innerText(),/1 \/ 5/);
  await page.locator('[data-step="cancel"]').click();
  await page.reload();await page.locator('.tab[data-page="runs"]').click();
  assert.match(await page.locator('.runitem').innerText(),/QA-sentinel-run-27[\s\S]*已取消/);
  assert.equal(await page.locator('[data-step="advance"]').count(),0);
  await page.screenshot({path:dir+'06-analysis-runs.png',fullPage:true});passed('mismatch blocks start; sentinel run persists; pause/cancel terminal guards');
  await page.locator('#scenario').selectOption('empty');
  assert.match(await page.locator('main').innerText(),/还没有业务图谱/);
  await page.screenshot({path:dir+'07-empty-project.png',fullPage:true});
  await page.locator('#scenario').selectOption('normal');passed('empty project with explicit creation entry');
  for(const width of [1440,1100,768,390]){
    await page.setViewportSize({width,height:1000});
    for(const name of ['graph','review','materials','runs']){
      await page.locator(`.tab[data-page="${name}"]`).click();
      const dimensions=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));
      assert.ok(dimensions.scroll<=dimensions.client+1,`${name}@${width} horizontal page overflow: ${JSON.stringify(dimensions)}`);
    }
    await page.locator('.tab[data-page="graph"]').click();
    await page.screenshot({path:dir+`08-responsive-${width}.png`,fullPage:true});
  }
  passed('all four views at 1440 / 1100 / 768 / 390: no page-level horizontal overflow');
  assert.deepEqual(errors,[]);passed('no browser console errors or uncaught exceptions');
  process.stdout.write(JSON.stringify({checks:checks.length,errors,viewportWidths:[1440,1100,768,390]},null,2)+'\n');
} finally {await context.close();await browser.close();}
