import assert from "node:assert/strict";
import test from "node:test";
import { candidateFixture } from "./support/source-truth-candidate-fixture.js";
import { owner, reader } from "./support/source-truth-database.js";
import { SourcePublicationService } from "../src/source-truth/publication-service.js";
import { SourceRenewalService } from "../src/source-truth/renewal-service.js";
import { SourceAdmissionService } from "../src/source-truth/admission-service.js";
import { createTraceabilityHttpServer } from "../src/api/http-server.js";
import { createSourceTruthHttpHandler } from "../src/source-truth/http-handler.js";
import { sourceTruthServices } from "../src/source-truth/services.js";
import { capturePolicy } from "../src/source-truth/policy.js";

test("B-10 same-bundle renewal appends a Receipt without recapture, altering old receipt or masking gaps", async (t) => {
  const gap = { ruleCode: "GIT_LFS_EXTERNAL", severity: "NON_BLOCKING", ruleVersion: "v1", affectedScope: "external-content", externalReference: null };
  const f = await candidateFixture(t, { git: true, gaps: [gap] });
  const candidate = await f.candidates.prepare(f.context);
  await f.advance("RECONCILING", "REVIEW_REQUIRED");
  const publication = new SourcePublicationService(f.repository, f.candidates);
  const confirmation = await publication.confirm(owner, f.context, { candidateId: candidate.id, gapSetId: candidate.gapSetId, reason: "接受已知限制", expiresAt: new Date(Date.now() + 1000).toISOString() });
  const original = await publication.seal(owner, f.context, { confirmationId: confirmation.id, clientToken: "original" });
  await new Promise((resolve) => setTimeout(resolve, 1100));
  const admission = new SourceAdmissionService(f.repository, f.candidates);
  const oldRef = { bundleId: original.bundle.id, receiptId: original.receipt.id };
  await assert.rejects(admission.qualify(reader, "workspace", oldRef), { code: "SOURCE_ACCEPTANCE_EXPIRED" });
  const services = sourceTruthServices({ repository: f.repository, blobs: f.blobs, policy: capturePolicy() });
  const server = createTraceabilityHttpServer({ application: {}, sourceTruthHandler: createSourceTruthHttpHandler({ services, authenticate: () => reader }) });
  await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve));
  t.after(() => new Promise((resolve) => { server.close(resolve); server.closeAllConnections(); }));
  const base = `http://127.0.0.1:${server.address().port}/v1/workspaces/workspace/source-truth/bundles/${oldRef.bundleId}`;
  const history = await fetch(`${base}/inventory-history?receiptId=${oldRef.receiptId}`);
  assert.equal(history.status, 200, "expiry must not make historical material inspection unavailable");
  const page = await history.json();
  assert.equal(page.items.length, 1);
  const fileUrl = `${base}/file-history?${new URLSearchParams({ receiptId: oldRef.receiptId, componentId: page.items[0].componentId, pathBytes: f.entry.pathBytes })}`;
  const bytes = await fetch(fileUrl);
  assert.equal(bytes.status, 200);
  assert.deepEqual(Buffer.from(await bytes.arrayBuffer()), f.bytes);
  assert.equal((await fetch(`${base}/inventory?receiptId=${oldRef.receiptId}`)).status, 409, "inspection is not F002 admission");
  await f.db.query("UPDATE source_truth_workspace SET restore_ready=false WHERE workspace_id='workspace'");
  assert.equal((await fetch(fileUrl)).status, 409, "historical reads must still enforce the restore integrity gate");
  await f.db.query("UPDATE source_truth_workspace SET restore_ready=true WHERE workspace_id='workspace'");
  const renewal = new SourceRenewalService(f.repository, f.candidates);
  const accept = await renewal.confirm(owner, "workspace", { ...oldRef, gapSetId: candidate.gapSetId, reason: "已重新核对外部材料限制", expiresAt: new Date(Date.now() + 60000).toISOString() });
  assert.ok(accept?.id);
  const retryConfirmation = await renewal.confirm(owner, "workspace", { ...oldRef, gapSetId: candidate.gapSetId, reason: accept.reason, expiresAt: accept.expiresAt });
  assert.equal(retryConfirmation.id, accept.id, "response loss must not manufacture another acceptance revision");
  const pending = await renewal.latest(owner, "workspace", oldRef);
  assert.equal(pending.confirmation.id, accept.id);
  assert.equal(pending.confirmation.currentlyValid, true);
  assert.equal(pending.operation, null);
  assert.equal(pending.result, null);
  assert.equal(await renewal.latest(reader, "workspace", oldRef), null, "a different member must not resume another member's confirmation by accident");
  await assert.rejects(renewal.issue(owner, "workspace", { ...oldRef, bundleId: "f".repeat(64), confirmationId: accept.id, clientToken: "wrong-bundle" }), { code: "SOURCE_RENEWAL_BINDING_CONFLICT" });
  const renewed = await renewal.issue(owner, "workspace", { ...oldRef, confirmationId: accept.id, clientToken: "renew" });
  const historicalReceipts = await fetch(`${base}/receipts?limit=1`);
  assert.equal(historicalReceipts.status, 200);
  const firstReceiptPage = await historicalReceipts.json();
  assert.equal(firstReceiptPage.items[0].id, renewed.receipt.id);
  assert.ok(firstReceiptPage.nextCursor);
  const oldReceiptPage = await (await fetch(`${base}/receipts?limit=1&cursor=${firstReceiptPage.nextCursor}`)).json();
  assert.equal(oldReceiptPage.items[0].id, oldRef.receiptId);
  assert.equal(oldReceiptPage.nextCursor, null);
  assert.equal(renewed.bundle.id, original.bundle.id);
  assert.notEqual(renewed.receipt.id, original.receipt.id);
  assert.equal(renewed.receipt.status, "READY_WITH_ACCEPTED_GAPS");
  assert.equal(renewed.receipt.gapSetId, original.receipt.gapSetId);
  assert.equal((await admission.qualify(reader, "workspace", { bundleId: renewed.bundle.id, receiptId: renewed.receipt.id })).gapCount, "1");
  await assert.rejects(admission.qualify(reader, "workspace", oldRef), { code: "SOURCE_ACCEPTANCE_EXPIRED" });
  const counts = await f.db.query("SELECT (SELECT count(*) FROM source_truth_run)::text AS runs,(SELECT count(*) FROM source_truth_bundle)::text AS bundles,(SELECT count(*) FROM source_truth_receipt)::text AS receipts");
  assert.deepEqual(counts.rows[0], { runs: "1", bundles: "1", receipts: "2" });
  const repeated = await renewal.issue(owner, "workspace", { ...oldRef, confirmationId: accept.id, clientToken: "renew-again" });
  assert.equal(repeated.receipt.id, renewed.receipt.id);
  assert.equal((await renewal.latest(owner, "workspace", oldRef)).result.receipt.id, renewed.receipt.id);
  await assert.rejects(renewal.issue(owner, "workspace", { ...oldRef, confirmationId: "different", clientToken: "renew-again" }), { code: "SOURCE_IDEMPOTENCY_CONFLICT" });
});
